version: 0.2
phases:
  install:
    commands:
      - npm i -g npm
      - npm ci --unsafe-perm
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
      - 'aws s3 sync "public/" "s3://tangible.media.mit.edu" --delete --acl "public-read"'
artifacts:
  baseDirectory: public
  files:
    - '**/*'
cache:
  paths:
    - '.cache/*'
    - node_modules/**/*
environment:
  nodejs:
    version: 18