version: 0.1
phases:
  pre_build:
    commands:
      - npm ci --unsafe-perm
  build:
    commands:
      - npm run build
artifacts:
  baseDirectory: public
  files:
    - '**/*'
cache:
  paths:
    - '.cache/*'
    - node_modules/**/*
