version: 0.1
phases:
  preBuild:
    commands:
      - yum install -y jq
      - npm ci
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - 'aws s3 sync "public/" "s3://tangible-website-prod" --delete --acl "public-read"'
artifacts:
  baseDirectory: public
  files:
    - '**/*'
cache:
  paths:
    - node_modules/**/*
