version: 0.1
phases:
  pre_build:
    commands:
      - npm ci --unsafe-perm
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - 'aws s3 sync "public/" "s3://tangible.media.mit.edu" --delete --acl "public-read"'
artifacts:
  baseDirectory: public
  files:
    - '**/*'
cache:
  paths:
    - '.cache/*'
    - node_modules/**/*
